version: '3.8'

services:
  auth-service:
    build:
      context: ./services/Auth
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./services/Auth/users.json:/usr/src/app/users.json
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # json-server:
  #   image: clue/json-server
  #   volumes:
  #     - ./services/Auth/users.json:/data/db.json
  #   ports:
  #     - "3000:80"

  image-service:
    build:
      context: ./services/image
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./services/image:/service_image
      - ./services/image/instance:/service_image/instance
      - ./services/image/uploads:/service_image/uploads
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000" ]
      interval: 10s
      timeout: 5s
      retries: 5

  comment-service:
    build:
      context: ./services/comment/rest-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/test
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=test
    networks:
      - app-network
    # youtube-clone-images:
    #   build: ./youtube-clone-images
    #   ports:
    #     - "4200:4200"
    #   command: ng serve
    #   depends_on:
    #     - auth-service
    #     - image-service
    #     - comment-service
    # conditions:
    #   - condition: service_healthy

networks:
  app-network:
    driver: bridge
