version: '3.8'
services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - .:/service image  # Montage du code source
      - ./instance:/service image/instance  # Montage du dossier de la base de données
      - ./uploads:/service image/uploads  # Montage du dossier des images téléchargées
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
