services:
  youtube-clone-images:
    build: .
    ports:
      - "4200:4200"
  comment-service:
    build: ../services/comment
    ports:
      - "8080:8080"
  image-service:
    build: ../services/image
    ports:
      - "5000:5000"
  auth-service:
    build: ../services/Auth
    ports:
      - "8081:8081"

