services:
  youtube-clone-images:
    build: .
    ports:
      - "4200:4200"
  comment-service:
    build: ./Backend/service comment/rest-service
    ports:
      - "8080:8080"
  image-service:
    build: ./Backend/service image
    ports:
      - "5000:5000"
  auth-service:
    build: ./Backend/Auth
    ports:
      - "8081:8081"

